namespace FxSheet

open ExcelDna.Integration
open System

type ILFunction() =
    static member xlfMap =
        Map.ofArray [| ("Count",XlCall.xlfCount); ("Isna",XlCall.xlfIsna); ("Iserror",XlCall.xlfIserror);
                       ("Sum",XlCall.xlfSum); ("Average",XlCall.xlfAverage); ("Min",XlCall.xlfMin); ("Max",XlCall.xlfMax);
                       ("Row",XlCall.xlfRow); ("Column",XlCall.xlfColumn); ("Na",XlCall.xlfNa); ("Npv",XlCall.xlfNpv);
                       ("Stdev",XlCall.xlfStdev); ("Dollar",XlCall.xlfDollar); ("Fixed",XlCall.xlfFixed); ("Sin",XlCall.xlfSin);
                       ("Cos",XlCall.xlfCos); ("Tan",XlCall.xlfTan); ("Atan",XlCall.xlfAtan); ("Pi",XlCall.xlfPi);
                       ("Sqrt",XlCall.xlfSqrt); ("Exp",XlCall.xlfExp); ("Ln",XlCall.xlfLn); ("Log10",XlCall.xlfLog10);
                       ("Abs",XlCall.xlfAbs); ("Int",XlCall.xlfInt); ("Sign",XlCall.xlfSign); ("Round",XlCall.xlfRound);
                       ("Lookup",XlCall.xlfLookup); ("Index",XlCall.xlfIndex); ("Rept",XlCall.xlfRept); ("Mid",XlCall.xlfMid);
                       ("Len",XlCall.xlfLen); ("Value",XlCall.xlfValue); ("TRUE",XlCall.xlfTrue); ("FALSE",XlCall.xlfFalse);
                       ("And",XlCall.xlfAnd); ("Or",XlCall.xlfOr); ("Not",XlCall.xlfNot); ("Mod",XlCall.xlfMod);
                       ("Dcount",XlCall.xlfDcount); ("Dsum",XlCall.xlfDsum); ("Daverage",XlCall.xlfDaverage); ("Dmin",XlCall.xlfDmin);
                       ("Dmax",XlCall.xlfDmax); ("Dstdev",XlCall.xlfDstdev); ("Var",XlCall.xlfVar); ("Dvar",XlCall.xlfDvar);
                       ("Text",XlCall.xlfText); ("Linest",XlCall.xlfLinest); ("Trend",XlCall.xlfTrend); ("Logest",XlCall.xlfLogest);
                       ("Growth",XlCall.xlfGrowth); ("Goto",XlCall.xlfGoto); ("Halt",XlCall.xlfHalt); ("Pv",XlCall.xlfPv);
                       ("Fv",XlCall.xlfFv); ("Nper",XlCall.xlfNper); ("Pmt",XlCall.xlfPmt); ("Rate",XlCall.xlfRate);
                       ("Mirr",XlCall.xlfMirr); ("Irr",XlCall.xlfIrr); ("Rand",XlCall.xlfRand); ("Match",XlCall.xlfMatch);
                       ("Date",XlCall.xlfDate); ("Time",XlCall.xlfTime); ("Day",XlCall.xlfDay); ("Month",XlCall.xlfMonth);
                       ("Year",XlCall.xlfYear); ("Weekday",XlCall.xlfWeekday); ("Hour",XlCall.xlfHour); ("Minute",XlCall.xlfMinute);
                       ("Second",XlCall.xlfSecond); ("Now",XlCall.xlfNow); ("Areas",XlCall.xlfAreas); ("Rows",XlCall.xlfRows);
                       ("Columns",XlCall.xlfColumns); ("Offset",XlCall.xlfOffset); ("Absref",XlCall.xlfAbsref);
                       ("Relref",XlCall.xlfRelref); ("Argument",XlCall.xlfArgument); ("Search",XlCall.xlfSearch);
                       ("Transpose",XlCall.xlfTranspose); ("Error",XlCall.xlfError); ("Step",XlCall.xlfStep); ("Type",XlCall.xlfType);
                       ("Echo",XlCall.xlfEcho); ("SetName",XlCall.xlfSetName); ("Caller",XlCall.xlfCaller); ("Deref",XlCall.xlfDeref);
                       ("Windows",XlCall.xlfWindows); ("Series",XlCall.xlfSeries); ("Documents",XlCall.xlfDocuments);
                       ("ActiveCell",XlCall.xlfActiveCell); ("Selection",XlCall.xlfSelection); ("Result",XlCall.xlfResult);
                       ("Atan2",XlCall.xlfAtan2); ("Asin",XlCall.xlfAsin); ("Acos",XlCall.xlfAcos); ("Choose",XlCall.xlfChoose);
                       ("Hlookup",XlCall.xlfHlookup); ("Vlookup",XlCall.xlfVlookup); ("Links",XlCall.xlfLinks);
                       ("Input",XlCall.xlfInput); ("Isref",XlCall.xlfIsref); ("GetFormula",XlCall.xlfGetFormula);
                       ("GetName",XlCall.xlfGetName); ("SetValue",XlCall.xlfSetValue); ("Log",XlCall.xlfLog); ("Exec",XlCall.xlfExec);
                       ("Char",XlCall.xlfChar); ("Lower",XlCall.xlfLower); ("Upper",XlCall.xlfUpper); ("Proper",XlCall.xlfProper);
                       ("Left",XlCall.xlfLeft); ("Right",XlCall.xlfRight); ("Exact",XlCall.xlfExact); ("Trim",XlCall.xlfTrim);
                       ("Replace",XlCall.xlfReplace); ("Substitute",XlCall.xlfSubstitute); ("Code",XlCall.xlfCode);
                       ("Names",XlCall.xlfNames); ("Directory",XlCall.xlfDirectory); ("Find",XlCall.xlfFind); ("Cell",XlCall.xlfCell);
                       ("Iserr",XlCall.xlfIserr); ("Istext",XlCall.xlfIstext); ("Isnumber",XlCall.xlfIsnumber);
                       ("Isblank",XlCall.xlfIsblank); ("T",XlCall.xlfT); ("N",XlCall.xlfN); ("Fopen",XlCall.xlfFopen);
                       ("Fclose",XlCall.xlfFclose); ("Fsize",XlCall.xlfFsize); ("Freadln",XlCall.xlfFreadln); ("Fread",XlCall.xlfFread);
                       ("Fwriteln",XlCall.xlfFwriteln); ("Fwrite",XlCall.xlfFwrite); ("Fpos",XlCall.xlfFpos);
                       ("Datevalue",XlCall.xlfDatevalue); ("Timevalue",XlCall.xlfTimevalue); ("Sln",XlCall.xlfSln);
                       ("Syd",XlCall.xlfSyd); ("Ddb",XlCall.xlfDdb); ("GetDef",XlCall.xlfGetDef); ("Reftext",XlCall.xlfReftext);
                       ("Textref",XlCall.xlfTextref); ("Indirect",XlCall.xlfIndirect); ("Register",XlCall.xlfRegister);
                       ("Call",XlCall.xlfCall); ("AddBar",XlCall.xlfAddBar); ("AddMenu",XlCall.xlfAddMenu);
                       ("AddCommand",XlCall.xlfAddCommand); ("EnableCommand",XlCall.xlfEnableCommand);
                       ("CheckCommand",XlCall.xlfCheckCommand); ("RenameCommand",XlCall.xlfRenameCommand);
                       ("ShowBar",XlCall.xlfShowBar); ("DeleteMenu",XlCall.xlfDeleteMenu); ("DeleteCommand",XlCall.xlfDeleteCommand);
                       ("GetChartItem",XlCall.xlfGetChartItem); ("DialogBox",XlCall.xlfDialogBox); ("Clean",XlCall.xlfClean);
                       ("Mdeterm",XlCall.xlfMdeterm); ("Minverse",XlCall.xlfMinverse); ("Mmult",XlCall.xlfMmult);
                       ("Files",XlCall.xlfFiles); ("Ipmt",XlCall.xlfIpmt); ("Ppmt",XlCall.xlfPpmt);
                       ("Counta",XlCall.xlfCounta); ("CancelKey",XlCall.xlfCancelKey); ("Initiate",XlCall.xlfInitiate);
                       ("Request",XlCall.xlfRequest); ("Poke",XlCall.xlfPoke); ("Execute",XlCall.xlfExecute);
                       ("Terminate",XlCall.xlfTerminate); ("Restart",XlCall.xlfRestart); ("Help",XlCall.xlfHelp);
                       ("GetBar",XlCall.xlfGetBar); ("Product",XlCall.xlfProduct); ("Fact",XlCall.xlfFact);
                       ("GetCell",XlCall.xlfGetCell); ("GetWorkspace",XlCall.xlfGetWorkspace); ("GetWindow",XlCall.xlfGetWindow);
                       ("GetDocument",XlCall.xlfGetDocument); ("Dproduct",XlCall.xlfDproduct); ("Isnontext",XlCall.xlfIsnontext);
                       ("GetNote",XlCall.xlfGetNote); ("Note",XlCall.xlfNote); ("Stdevp",XlCall.xlfStdevp); ("Varp",XlCall.xlfVarp);
                       ("Dstdevp",XlCall.xlfDstdevp); ("Dvarp",XlCall.xlfDvarp); ("Trunc",XlCall.xlfTrunc);
                       ("Islogical",XlCall.xlfIslogical); ("Dcounta",XlCall.xlfDcounta); ("DeleteBar",XlCall.xlfDeleteBar);
                       ("Unregister",XlCall.xlfUnregister); ("Usdollar",XlCall.xlfUsdollar); ("Findb",XlCall.xlfFindb);
                       ("Searchb",XlCall.xlfSearchb); ("Replaceb",XlCall.xlfReplaceb); ("Leftb",XlCall.xlfLeftb);
                       ("Rightb",XlCall.xlfRightb); ("Midb",XlCall.xlfMidb); ("Lenb",XlCall.xlfLenb); ("Roundup",XlCall.xlfRoundup);
                       ("Rounddown",XlCall.xlfRounddown); ("Asc",XlCall.xlfAsc); ("Dbcs",XlCall.xlfDbcs); ("Rank",XlCall.xlfRank);
                       ("Address",XlCall.xlfAddress); ("Days360",XlCall.xlfDays360); ("Today",XlCall.xlfToday); ("Vdb",XlCall.xlfVdb);
                       ("Median",XlCall.xlfMedian); ("Sumproduct",XlCall.xlfSumproduct); ("Sinh",XlCall.xlfSinh);
                       ("Cosh",XlCall.xlfCosh); ("Tanh",XlCall.xlfTanh); ("Asinh",XlCall.xlfAsinh); ("Acosh",XlCall.xlfAcosh);
                       ("Atanh",XlCall.xlfAtanh); ("Dget",XlCall.xlfDget); ("CreateObject",XlCall.xlfCreateObject);
                       ("Volatile",XlCall.xlfVolatile); ("LastError",XlCall.xlfLastError); ("CustomUndo",XlCall.xlfCustomUndo);
                       ("CustomRepeat",XlCall.xlfCustomRepeat); ("FormulaConvert",XlCall.xlfFormulaConvert);
                       ("GetLinkInfo",XlCall.xlfGetLinkInfo); ("TextBox",XlCall.xlfTextBox); ("Info",XlCall.xlfInfo);
                       ("Group",XlCall.xlfGroup); ("GetObject",XlCall.xlfGetObject); ("Db",XlCall.xlfDb); ("Pause",XlCall.xlfPause);
                       ("Resume",XlCall.xlfResume); ("Frequency",XlCall.xlfFrequency); ("AddToolbar",XlCall.xlfAddToolbar);
                       ("DeleteToolbar",XlCall.xlfDeleteToolbar); ("ResetToolbar",XlCall.xlfResetToolbar);
                       ("Evaluate",XlCall.xlfEvaluate); ("GetToolbar",XlCall.xlfGetToolbar); ("GetTool",XlCall.xlfGetTool);
                       ("SpellingCheck",XlCall.xlfSpellingCheck); ("ErrorType",XlCall.xlfErrorType); ("AppTitle",XlCall.xlfAppTitle);
                       ("indowTitle",XlCall.xlfWindowTitle); ("SaveToolbar",XlCall.xlfSaveToolbar); ("EnableTool",XlCall.xlfEnableTool);
                       ("PressTool",XlCall.xlfPressTool); ("RegisterId",XlCall.xlfRegisterId); ("GetWorkbook",XlCall.xlfGetWorkbook);
                       ("Avedev",XlCall.xlfAvedev); ("Betadist",XlCall.xlfBetadist); ("Gammaln",XlCall.xlfGammaln);
                       ("Betainv",XlCall.xlfBetainv); ("Binomdist",XlCall.xlfBinomdist); ("Chidist",XlCall.xlfChidist);
                       ("Chiinv",XlCall.xlfChiinv); ("Combin",XlCall.xlfCombin); ("Confidence",XlCall.xlfConfidence);
                       ("Critbinom",XlCall.xlfCritbinom); ("Even",XlCall.xlfEven); ("Expondist",XlCall.xlfExpondist);
                       ("Fdist",XlCall.xlfFdist); ("Finv",XlCall.xlfFinv); ("Fisher",XlCall.xlfFisher);
                       ("Fisherinv",XlCall.xlfFisherinv); ("Floor",XlCall.xlfFloor); ("Gammadist",XlCall.xlfGammadist);
                       ("Gammainv",XlCall.xlfGammainv); ("Ceiling",XlCall.xlfCeiling); ("Hypgeomdist",XlCall.xlfHypgeomdist);
                       ("Lognormdist",XlCall.xlfLognormdist); ("Loginv",XlCall.xlfLoginv); ("Negbinomdist",XlCall.xlfNegbinomdist);
                       ("Normdist",XlCall.xlfNormdist); ("Normsdist",XlCall.xlfNormsdist); ("Norminv",XlCall.xlfNorminv);
                       ("Normsinv",XlCall.xlfNormsinv); ("Standardize",XlCall.xlfStandardize); ("Odd",XlCall.xlfOdd);
                       ("Permut",XlCall.xlfPermut); ("Poisson",XlCall.xlfPoisson); ("Tdist",XlCall.xlfTdist);
                       ("Weibull",XlCall.xlfWeibull); ("Sumxmy2",XlCall.xlfSumxmy2); ("Sumx2my2",XlCall.xlfSumx2my2);
                       ("Sumx2py2",XlCall.xlfSumx2py2); ("Chitest",XlCall.xlfChitest); ("Correl",XlCall.xlfCorrel);
                       ("Covar",XlCall.xlfCovar); ("Forecast",XlCall.xlfForecast); ("Ftest",XlCall.xlfFtest);
                       ("Intercept",XlCall.xlfIntercept); ("Pearson",XlCall.xlfPearson); ("Rsq",XlCall.xlfRsq);
                       ("Steyx",XlCall.xlfSteyx); ("Slope",XlCall.xlfSlope); ("Ttest",XlCall.xlfTtest); ("Prob",XlCall.xlfProb);
                       ("Devsq",XlCall.xlfDevsq); ("Geomean",XlCall.xlfGeomean); ("Harmean",XlCall.xlfHarmean);
                       ("Sumsq",XlCall.xlfSumsq); ("Kurt",XlCall.xlfKurt); ("Skew",XlCall.xlfSkew); ("Ztest",XlCall.xlfZtest);
                       ("Large",XlCall.xlfLarge); ("Small",XlCall.xlfSmall); ("Quartile",XlCall.xlfQuartile);
                       ("Percentile",XlCall.xlfPercentile); ("Percentrank",XlCall.xlfPercentrank); ("Mode",XlCall.xlfMode);
                       ("Trimmean",XlCall.xlfTrimmean); ("Tinv",XlCall.xlfTinv); ("MovieCommand",XlCall.xlfMovieCommand);
                       ("GetMovie",XlCall.xlfGetMovie); ("Concatenate",XlCall.xlfConcatenate); ("Power",XlCall.xlfPower);
                       ("PivotAddData",XlCall.xlfPivotAddData); ("GetPivotTable",XlCall.xlfGetPivotTable);
                       ("GetPivotField",XlCall.xlfGetPivotField); ("GetPivotItem",XlCall.xlfGetPivotItem);
                       ("Radians",XlCall.xlfRadians); ("Degrees",XlCall.xlfDegrees); ("Subtotal",XlCall.xlfSubtotal);
                       ("Sumif",XlCall.xlfSumif); ("Countif",XlCall.xlfCountif); ("Countblank",XlCall.xlfCountblank);
                       ("ScenarioGet",XlCall.xlfScenarioGet); ("OptionsListsGet",XlCall.xlfOptionsListsGet); ("Ispmt",XlCall.xlfIspmt);
                       ("Datedif",XlCall.xlfDatedif); ("Datestring",XlCall.xlfDatestring); ("Numberstring",XlCall.xlfNumberstring);
                       ("Roman",XlCall.xlfRoman); ("OpenDialog",XlCall.xlfOpenDialog); ("SaveDialog",XlCall.xlfSaveDialog);
                       ("ViewGet",XlCall.xlfViewGet); ("Getpivotdata",XlCall.xlfGetpivotdata); ("Hyperlink",XlCall.xlfHyperlink);
                       ("Phonetic",XlCall.xlfPhonetic); ("Averagea",XlCall.xlfAveragea); ("Maxa",XlCall.xlfMaxa);
                       ("Mina",XlCall.xlfMina); ("Stdevpa",XlCall.xlfStdevpa); ("Varpa",XlCall.xlfVarpa); ("Stdeva",XlCall.xlfStdeva);
                       ("Vara",XlCall.xlfVara); ("Bahttext",XlCall.xlfBahttext); ("Thaidayofweek",XlCall.xlfThaidayofweek);
                       ("Thaidigit",XlCall.xlfThaidigit); ("Thaimonthofyear",XlCall.xlfThaimonthofyear);
                       ("Thainumsound",XlCall.xlfThainumsound); ("Thainumstring",XlCall.xlfThainumstring);
                       ("Thaistringlength",XlCall.xlfThaistringlength); ("Isthaidigit",XlCall.xlfIsthaidigit);
                       ("Roundbahtdown",XlCall.xlfRoundbahtdown); ("Roundbahtup",XlCall.xlfRoundbahtup);
                       ("Thaiyear",XlCall.xlfThaiyear); ("Rtd",XlCall.xlfRtd); ("Cubevalue",XlCall.xlfCubevalue);
                       ("Cubemember",XlCall.xlfCubemember); ("Cubememberproperty",XlCall.xlfCubememberproperty);
                       ("Cuberankedmember",XlCall.xlfCuberankedmember); ("Hex2bin",XlCall.xlfHex2bin); ("Hex2dec",XlCall.xlfHex2dec);
                       ("Hex2oct",XlCall.xlfHex2oct); ("Dec2bin",XlCall.xlfDec2bin); ("Dec2hex",XlCall.xlfDec2hex);
                       ("Dec2oct",XlCall.xlfDec2oct); ("Oct2bin",XlCall.xlfOct2bin); ("Oct2hex",XlCall.xlfOct2hex);
                       ("Oct2dec",XlCall.xlfOct2dec); ("Bin2dec",XlCall.xlfBin2dec); ("Bin2oct",XlCall.xlfBin2oct); 
                       ("Bin2hex",XlCall.xlfBin2hex); ("Imsub",XlCall.xlfImsub); ("Imdiv",XlCall.xlfImdiv);
                       ("Impower",XlCall.xlfImpower); ("Imabs",XlCall.xlfImabs); ("Imsqrt",XlCall.xlfImsqrt); ("Imln",XlCall.xlfImln);
                       ("Imlog2",XlCall.xlfImlog2); ("Imlog10",XlCall.xlfImlog10); ("Imsin",XlCall.xlfImsin); ("Imcos",XlCall.xlfImcos);
                       ("Imexp",XlCall.xlfImexp); ("Imargument",XlCall.xlfImargument); ("Imconjugate",XlCall.xlfImconjugate);
                       ("Imaginary",XlCall.xlfImaginary); ("Imreal",XlCall.xlfImreal); ("Complex",XlCall.xlfComplex);
                       ("Imsum",XlCall.xlfImsum); ("Improduct",XlCall.xlfImproduct); ("Seriessum",XlCall.xlfSeriessum);
                       ("Factdouble",XlCall.xlfFactdouble); ("Sqrtpi",XlCall.xlfSqrtpi); ("Quotient",XlCall.xlfQuotient);
                       ("Delta",XlCall.xlfDelta); ("Gestep",XlCall.xlfGestep); ("Iseven",XlCall.xlfIseven); ("Isodd",XlCall.xlfIsodd);
                       ("Mround",XlCall.xlfMround); ("Erf",XlCall.xlfErf); ("Erfc",XlCall.xlfErfc); ("Besselj",XlCall.xlfBesselj);
                       ("Besselk",XlCall.xlfBesselk); ("Bessely",XlCall.xlfBessely); ("Besseli",XlCall.xlfBesseli);
                       ("Xirr",XlCall.xlfXirr); ("Xnpv",XlCall.xlfXnpv); ("Pricemat",XlCall.xlfPricemat);
                       ("Yieldmat",XlCall.xlfYieldmat); ("Intrate",XlCall.xlfIntrate); ("Received",XlCall.xlfReceived);
                       ("Disc",XlCall.xlfDisc); ("Pricedisc",XlCall.xlfPricedisc); ("Yielddisc",XlCall.xlfYielddisc);
                       ("Tbilleq",XlCall.xlfTbilleq); ("Tbillprice",XlCall.xlfTbillprice); ("Tbillyield",XlCall.xlfTbillyield);
                       ("Price",XlCall.xlfPrice); ("Yield",XlCall.xlfYield); ("Dollarde",XlCall.xlfDollarde);
                       ("Dollarfr",XlCall.xlfDollarfr); ("Nominal",XlCall.xlfNominal); ("Effect",XlCall.xlfEffect);
                       ("Cumprinc",XlCall.xlfCumprinc); ("Cumipmt",XlCall.xlfCumipmt); ("Edate",XlCall.xlfEdate);
                       ("Eomonth",XlCall.xlfEomonth); ("Yearfrac",XlCall.xlfYearfrac); ("Coupdaybs",XlCall.xlfCoupdaybs);
                       ("Coupdays",XlCall.xlfCoupdays); ("Coupdaysnc",XlCall.xlfCoupdaysnc); ("Coupncd",XlCall.xlfCoupncd);
                       ("Coupnum",XlCall.xlfCoupnum); ("Couppcd",XlCall.xlfCouppcd); ("Duration",XlCall.xlfDuration);
                       ("Mduration",XlCall.xlfMduration); ("Oddlprice",XlCall.xlfOddlprice); ("Oddlyield",XlCall.xlfOddlyield);
                       ("Oddfprice",XlCall.xlfOddfprice); ("Oddfyield",XlCall.xlfOddfyield); ("Randbetween",XlCall.xlfRandbetween);
                       ("Weeknum",XlCall.xlfWeeknum); ("Amordegrc",XlCall.xlfAmordegrc); ("Amorlinc",XlCall.xlfAmorlinc);
                       ("Convert",XlCall.xlfConvert); ("Accrint",XlCall.xlfAccrint); ("Accrintm",XlCall.xlfAccrintm);
                       ("Workday",XlCall.xlfWorkday); ("Networkdays",XlCall.xlfNetworkdays); ("Gcd",XlCall.xlfGcd);
                       ("Multinomial",XlCall.xlfMultinomial); ("Lcm",XlCall.xlfLcm); ("Fvschedule",XlCall.xlfFvschedule);
                       ("Cubekpimember",XlCall.xlfCubekpimember); ("Cubeset",XlCall.xlfCubeset);
                       ("Cubesetcount",XlCall.xlfCubesetcount); ("Iferror",XlCall.xlfIferror); ("Countifs",XlCall.xlfCountifs);
                       ("Sumifs",XlCall.xlfSumifs); ("Averageif",XlCall.xlfAverageif); ("Averageifs",XlCall.xlfAverageifs);
                       ("Aggregate",XlCall.xlfAggregate); ("Binom_dist",XlCall.xlfBinom_dist); ("Binom_inv",XlCall.xlfBinom_inv);
                       ("Confidence_norm",XlCall.xlfConfidence_norm); ("Confidence_t",XlCall.xlfConfidence_t);
                       ("Chisq_test",XlCall.xlfChisq_test); ("F_test",XlCall.xlfF_test); ("Covariance_p",XlCall.xlfCovariance_p);
                       ("Covariance_s",XlCall.xlfCovariance_s); ("Expon_dist",XlCall.xlfExpon_dist);
                       ("Gamma_dist",XlCall.xlfGamma_dist); ("Gamma_inv",XlCall.xlfGamma_inv); ("Mode_mult",XlCall.xlfMode_mult);
                       ("Mode_sngl",XlCall.xlfMode_sngl); ("Norm_dist",XlCall.xlfNorm_dist); ("Norm_inv",XlCall.xlfNorm_inv);
                       ("Percentile_exc",XlCall.xlfPercentile_exc); ("Percentile_inc",XlCall.xlfPercentile_inc);
                       ("Percentrank_exc",XlCall.xlfPercentrank_exc); ("Percentrank_inc",XlCall.xlfPercentrank_inc);
                       ("Poisson_dist",XlCall.xlfPoisson_dist); ("Quartile_exc",XlCall.xlfQuartile_exc);
                       ("Quartile_inc",XlCall.xlfQuartile_inc); ("Rank_avg",XlCall.xlfRank_avg); ("Rank_eq",XlCall.xlfRank_eq);
                       ("Stdev_s",XlCall.xlfStdev_s); ("Stdev_p",XlCall.xlfStdev_p); ("T_dist",XlCall.xlfT_dist);
                       ("T_dist_2t",XlCall.xlfT_dist_2t); ("T_dist_rt",XlCall.xlfT_dist_rt); ("T_inv",XlCall.xlfT_inv);
                       ("T_inv_2t",XlCall.xlfT_inv_2t); ("Var_s",XlCall.xlfVar_s); ("Var_p",XlCall.xlfVar_p);
                       ("Weibull_dist",XlCall.xlfWeibull_dist); ("Networkdays_intl",XlCall.xlfNetworkdays_intl);
                       ("Workday_intl",XlCall.xlfWorkday_intl); ("Ecma_ceiling",XlCall.xlfEcma_ceiling);
                       ("Iso_ceiling",XlCall.xlfIso_ceiling); ("Beta_dist",XlCall.xlfBeta_dist); ("Beta_inv",XlCall.xlfBeta_inv);
                       ("Chisq_dist",XlCall.xlfChisq_dist); ("Chisq_dist_rt",XlCall.xlfChisq_dist_rt);
                       ("Chisq_inv",XlCall.xlfChisq_inv); ("Chisq_inv_rt",XlCall.xlfChisq_inv_rt); ("F_dist",XlCall.xlfF_dist);
                       ("F_dist_rt",XlCall.xlfF_dist_rt); ("F_inv",XlCall.xlfF_inv); ("F_inv_rt",XlCall.xlfF_inv_rt);
                       ("Hypgeom_dist",XlCall.xlfHypgeom_dist); ("Lognorm_dist",XlCall.xlfLognorm_dist);
                       ("Lognorm_inv",XlCall.xlfLognorm_inv); ("Negbinom_dist",XlCall.xlfNegbinom_dist);
                       ("Norm_s_dist",XlCall.xlfNorm_s_dist); ("Norm_s_inv",XlCall.xlfNorm_s_inv); ("T_test",XlCall.xlfT_test);
                       ("Z_test",XlCall.xlfZ_test); ("Erf_precise",XlCall.xlfErf_precise); ("Erfc_precise",XlCall.xlfErfc_precise);
                       ("Gammaln_precise",XlCall.xlfGammaln_precise); ("Ceiling_precise",XlCall.xlfCeiling_precise);
                       ("Floor_precise",XlCall.xlfFloor_precise); ("Acot",XlCall.xlfAcot); ("Acoth",XlCall.xlfAcoth);
                       ("Cot",XlCall.xlfCot); ("Coth",XlCall.xlfCoth); ("Csc",XlCall.xlfCsc); ("Csch",XlCall.xlfCsch);
                       ("Sec",XlCall.xlfSec); ("Sech",XlCall.xlfSech); ("Imtan",XlCall.xlfImtan); ("Imcot",XlCall.xlfImcot);
                       ("Imcsc",XlCall.xlfImcsc); ("Imcsch",XlCall.xlfImcsch); ("Imsec",XlCall.xlfImsec); ("Imsech",XlCall.xlfImsech);
                       ("Bitand",XlCall.xlfBitand); ("Bitor",XlCall.xlfBitor); ("Bitxor",XlCall.xlfBitxor);
                       ("Bitlshift",XlCall.xlfBitlshift); ("Bitrshift",XlCall.xlfBitrshift); ("Permutationa",XlCall.xlfPermutationa);
                       ("Combina",XlCall.xlfCombina); ("Xor",XlCall.xlfXor); ("Pduration",XlCall.xlfPduration);
                       ("Base",XlCall.xlfBase); ("Decimal",XlCall.xlfDecimal); ("Days",XlCall.xlfDays);
                       ("Binom_dist_range",XlCall.xlfBinom_dist_range); ("Gamma",XlCall.xlfGamma); ("Skew_p",XlCall.xlfSkew_p);
                       ("Gauss",XlCall.xlfGauss); ("Phi",XlCall.xlfPhi); ("Rri",XlCall.xlfRri); ("Unichar",XlCall.xlfUnichar);
                       ("Unicode",XlCall.xlfUnicode); ("Munit",XlCall.xlfMunit); ("Arabic",XlCall.xlfArabic);
                       ("Isoweeknum",XlCall.xlfIsoweeknum); ("Numbervalue",XlCall.xlfNumbervalue); ("Sheet",XlCall.xlfSheet);
                       ("Sheets",XlCall.xlfSheets); ("Formulatext",XlCall.xlfFormulatext); ("Isformula",XlCall.xlfIsformula);
                       ("Ifna",XlCall.xlfIfna); ("Ceiling_math",XlCall.xlfCeiling_math); ("Floor_math",XlCall.xlfFloor_math);
                       ("Imsinh",XlCall.xlfImsinh); ("Imcosh",XlCall.xlfImcosh); ("Filterxml",XlCall.xlfFilterxml);
                       ("Webservice",XlCall.xlfWebservice); ("Encodeurl",XlCall.xlfEncodeurl) |]
    (* TODO: inline this... *)
    static member runXlf(xlFunction: int, [<ParamArray>] xs : array<obj>) : double =
        let r = Microsoft.FSharp.Core.Operators.ref null
        XlCall.TryExcel(xlFunction, r, xs) |> ignore
        r.Value :?> double
    static member runUdf([<ParamArray>] xs : array<obj>) : double =
        let r = Microsoft.FSharp.Core.Operators.ref null
        XlCall.TryExcel(XlCall.xlUDF, r, xs) |> ignore
        r.Value :?> double